libraries:
#MOVIE LIBRARY CONFIG FOR SCHEDULED COLLECTIONS TO BE DELETED WHEN OUT OF SEASON
  Scheduled:
    library_name: Movies
    report_path: config/missing/Scheduled_report.yml
    template_variables:
      use_separator: false
    collection_files:
    - folder: /config/Scheduled/
      asset_directory: config/assets/plex/Collections
    - pmm: year
      asset_directory: config/assets/plex/Collections
      template_variables:
        limit: 25
        sort_by: critic_rating.desc
        data:
          starting: current_year-1
          ending: current_year-1
        summary_format: Top <<limit>> movies of <<key>>. Sorted by critic rating.
        collection_section: '010'
        schedule: range(01/01-02/28)
    settings:
      delete_not_scheduled: true
      asset_directory: config/assets/plex/Movies

#MAIN MOVIE LIBRARY CONFIG
  Movies:
    collection_files:
    - default: basic
    - default: imdb
    - default: trakt
    - default: resolution
      template_variables:
        sep_style: gold
        exclude:
        - sd
        sort_by: title.asc
      folder: config/Movies/
      asset_directory: config/assets/plex/Movies
      asset_depth: 2
    - pmm: based
      asset_directory: config/assets/plex/Collections
      template_variables:
        summary_true_story: Films based on or inspired by a true story.
        summary_book: Films based on or inspired by a book.
        summary_video_game: Films based on or inspired by a video game.
        summary_comic: Films based on or inspired by a comic.
        schedule: all[weekly(thursday), hourly(06-07)]
    - pmm: decade
      asset_directory: config/assets/plex/Collections
      template_variables:
        exclude:
        - 1960
        limit: 100
        limit_1970: 25
        summary_format: Top <<limit>> movies of the <<key>>s. Sorted by critic rating.
        summary_1970: Top <<limit_1970>> movies of the <<key>>s. Sorted by critic rating.
        minimum_items: 25
    - pmm: genre
      asset_directory: config/assets/plex/Collections
      template_variables:
        sort_by: title.asc
        exclude:
        - Horror #IN SCHEDULED LIBRARY
        - War #GENRE.YML
        - Western #GENRE.YML
        - Spy #GENRE.YML
        - Sport #GENRE.YML
        minimum_items: 10
    - pmm: imdb
      asset_directory: config/assets/plex/Collections
      template_variables:
        use_lowest: false
        order_top: 3
        order_popular: 3
    - pmm: seasonal
      asset_directory: config/assets/plex/Collections
      template_variables:
        emoji: ''
        schedule_easter: range(03/20-04/05)
        schedule_independence: range(06/28-07/05)
        schedule_labor: range(09/01-09/05)
        schedule_thanksgiving: range(11/01-11/24)
        schedule_veteran: range(11/01-11/12)
        schedule_valentine: range(02/05-02/15)
        exclude:
        - christmas #IN SCHEDULED LIBRARY
        - easter #NOT ENOUGH FILMS
        - halloween #IN SCHEDULED LIBRARY
        - latinx #NOT ENOUGH FILMS
        - women #INOP DUE TO IMDB CHANGES
    - pmm: tautulli
      asset_directory: config/assets/plex/Collections
      template_variables:
        use_watched: true
        list_days: 14
        list_size: 25
        summary_popular: A collection of the most watched movies on this Plex server.
        order_popular: 1
#    - pmm: trakt
#      asset_directory: config/assets/plex/Collections
#      template_variables:
#        use_collected: false
#        use_recommended: false
#        use_watched: false
#        order_popular: 4
#        order_trending: 4
#        schedule: weekly(monday)
    - pmm: universe
      asset_directory: config/assets/plex/Collections
      template_variables:
        trakt_list_avp: https://trakt.tv/users/oldmankestis/lists/alien-predator
        trakt_list_mcu: https://trakt.tv/users/oldmankestis/lists/marvel-cinematic-universe
        trakt_list_star: https://trakt.tv/users/oldmankestis/lists/star-wars
        trakt_list_trek: https://trakt.tv/users/oldmankestis/lists/star-trek
        trakt_list_xmen: https://trakt.tv/users/oldmankestis/lists/x-men-collection
        summary_mcu: The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films produced by Marvel Studios. Sorted in chronological order.
        summary_xmen: The X-Men Collection. Sorted in chronological order.
        minimum_items: 3
        append_data:
          star: Star Wars Saga
          trek: Star Trek Universe
          xmen: X-Men Collection
        exclude:
        - marvel #FRANCHISE.YML
        - mummy #FRANCHISE.YML
        - rocky #NOT IN LIBRARY
        collection_section: '106'
    operations:
      mass_poster_update:
        source: tmdb
      mass_genre_update: tmdb
      mass_audience_rating_update: tmdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: trakt_user
      assets_for_all: true
    settings:
      asset_directory: config/assets/plex/Movies
      asset_depth: 2
      show_missing_assets: false
#######################################################
##                   TV LIBRARIES                    ##
#######################################################

#TV SHOWS CONFIG
      # see the wiki for how to use local files, folders, URLs, or files from git

  TV Shows:
    collection_files:
    - default: basic
    - default: imdb
    - file: config/franchise.yml
    remove_overlays: false
    operations:
      assets_for_all: true
    settings:
      asset_directory: config/assets/plex/Movies
settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 60
  asset_directory: config/assets/plex/Movies
  asset_folders: true
  asset_depth: 2
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: false
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: true
  show_missing: false
  show_missing_assets: false
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 75
  show_unfiltered: false
webhooks:                            # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex:                                # Can be individually specified per library as well; REQUIRED for the script to run
  url: 
  token: 
  timeout: 60
  db_cache:
  clean_bundles: false
  empty_trash: true
  optimize: true
  verify_ssl:
tmdb:                                # REQUIRED for the script to run
  apikey: 
  language: en
  cache_expiration: 60
  region:
tautulli:                            # Can be individually specified per library as well
  url: 
  apikey: 
radarr:                              # Can be individually specified per library as well
  url: radarr_url
  token: 
  add_missing: true
  add_existing: false
  upgrade_existing: true
  monitor_existing: true
  root_folder_path: radarr_root
  monitor: true
  availability: announced
  quality_profile: HD-1080p
  tag: kometa
  search: false
  radarr_path:
  plex_path:
  ignore_cache: true
sonarr:                              # Can be individually specified per library as well
  url: sonarr_url
  token: 191cfc5edd854dcf93bb2df0d2bcad6e
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: Root_folder 
  monitor: all
  quality_profile: Default
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  ignore_cache: false
trakt:
  client_id: 
  client_secret: 
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token: 
    token_type: Bearer
    expires_in: 7889238
    refresh_token: 
    scope: public
    created_at: 1751369646
